### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by TheNeikos**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
this needs rebase, right?

**Comment by TheNeikos** [comment]
> this needs rebase, right?

Yes, once #221 is merged

**Comment by matthiasbeyer** [comment]
it is.

**Comment by TheNeikos** [comment]
Done

**Review by matthiasbeyer — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
bors merge

**Pull request merged**
